package accounts

import (
	"crypto/rand"
	"crypto/subtle"
	"encoding/base64"
	"errors"
	"fmt"
	"log/slog"
	"strconv"
	"strings"
	"unicode/utf8"

	"golang.org/x/crypto/argon2"
)

/*
This file is where Convia deliberately contradicts itself, and the contradiction
is the point.

`M07-004` records that an application key is stored as a plain SHA-256 digest,
and gives the reason: the secret is twenty-six base32 characters from
crypto/rand, so roughly 130 bits, which cannot be searched at any rate a slow
hash would meaningfully change. Adding a key-derivation function there would buy
nothing and cost latency on every authenticated request.

A person's password is the opposite kind of secret. It is short, it is chosen,
it is often reused, and it *can* be searched — so the same reasoning arrives at
the opposite conclusion. Convia therefore holds two kinds of secret under two
different rules, and the rule is chosen by where the entropy came from rather
than by habit.

A session token, generated by Convia a few files away, goes back to SHA-256 for
the original reason.
*/

const (
	/*
		MinimumPasswordLength is the shortest password Convia accepts.

		NIST SP 800-63B asks for length and nothing else: no composition rules,
		no forced rotation, no character-class requirements. Every one of those
		makes passwords more predictable rather than less, because people
		satisfy them in the same few ways. Twelve is above the floor that
		guidance sets and below the point where people start writing them down.
	*/
	MinimumPasswordLength = 12

	/*
		MaximumPasswordLength bounds what Convia will hash.

		argon2id has no length limit of its own, unlike bcrypt, so this is not a
		correctness bound — it is a refusal to spend memory and time hashing a
		megabyte somebody pasted. It is far above any password a person types.
	*/
	MaximumPasswordLength = 256

	/*
		The argon2id cost parameters.

		These are the values the RFC 9106 second recommendation gives for a
		memory-constrained setting: 64 MiB, three passes, one lane. On the
		hardware Convia runs on that is tens of milliseconds, which is
		imperceptible when signing in and expensive in bulk, which is the trade
		this is for.

		They travel *inside* each stored digest rather than being read from
		here at verification time. That is what lets the cost be raised later
		without invalidating everybody's password at once: an old digest is
		still verifiable by its own parameters, and can be re-hashed with the
		new ones the next time its owner signs in.
	*/
	argonMemory      = 64 * 1024
	argonIterations  = 3
	argonParallelism = 1
	argonSaltLength  = 16
	argonKeyLength   = 32

	// digestVariant names the algorithm inside the encoded digest, so a future
	// one can be told apart rather than guessed at.
	digestVariant = "argon2id"

	// redacted is what a password renders as, everywhere, always.
	redacted = "[redacted]"
)

/*
ErrPasswordUnreadable reports a stored digest this version cannot verify.

It is not a wrong password. It means the row holds something this build does not
understand — a variant from a newer version, or a corrupted value — and the
difference matters to an operator even though the person signing in is told the
same thing either way.
*/
var ErrPasswordUnreadable = errors.New("the stored password digest cannot be read")

/*
Password is a password in the clear, which Convia holds only in memory and only
for as long as it takes to hash or compare it.

It is a distinct type so that it cannot be passed where an ordinary string is
expected, and so that every place one is handled is easy to find. It renders as
[redacted] through every formatting path Go offers, which is what keeps it out
of a log line written by somebody who did not think about it.
*/
type Password string

// String hides the password from %s, %v, and anything that calls it.
func (Password) String() string { return redacted }

// GoString hides the password from the %#v verb, which does not consult String.
func (Password) GoString() string { return redacted }

// LogValue hides the password from slog, which resolves this before formatting.
func (Password) LogValue() slog.Value { return slog.StringValue(redacted) }

/*
Digest is the stored form of a password: the algorithm, its parameters, the
salt, and the derived key, in the encoded shape argon2 implementations agree on.

It is a distinct type for the same reason Password is, and it is redacted for a
weaker but real reason: a digest is not a password, but publishing one hands an
attacker everything they need to attack it offline at their leisure.
*/
type Digest string

// String hides the digest from %s, %v, and anything that calls it.
func (Digest) String() string { return redacted }

// GoString hides the digest from the %#v verb.
func (Digest) GoString() string { return redacted }

// LogValue hides the digest from slog.
func (Digest) LogValue() slog.Value { return slog.StringValue(redacted) }

/*
The compile-time assertions that keep the redaction honest.

Without them, removing one of the methods above would leave the type formatting
its own contents again, and nothing would fail until a password appeared in a
log.
*/
var (
	_ fmt.Stringer   = Password("")
	_ fmt.GoStringer = Password("")
	_ slog.LogValuer = Password("")

	_ fmt.Stringer   = Digest("")
	_ fmt.GoStringer = Digest("")
	_ slog.LogValuer = Digest("")
)

/*
Hash derives the stored form of a password.

The salt is fresh per password, so two people who chose the same one do not
share a digest, and a precomputed table is worthless against either.
*/
func Hash(password Password) (Digest, error) {
	salt := make([]byte, argonSaltLength)
	if _, err := rand.Read(salt); err != nil {
		return "", fmt.Errorf("read salt: %w", err)
	}

	return encode(salt, derive(password, salt, argonMemory, argonIterations, argonParallelism)), nil
}

/*
Verify reports whether a password produces a stored digest.

The comparison is constant time. It matters less here than for a bearer key —
an attacker who can already submit password guesses learns little from timing
one byte at a time — but the cost is nothing and the habit is worth keeping.
*/
func Verify(stored Digest, password Password) (bool, error) {
	salt, expected, memory, iterations, parallelism, err := decode(stored)
	if err != nil {
		return false, err
	}

	derived := derive(password, salt, memory, iterations, parallelism)
	return subtle.ConstantTimeCompare(expected, derived) == 1, nil
}

/*
Stale reports whether a digest was made with weaker parameters than Convia now
uses.

Raising the cost is only useful if existing passwords eventually move to it, and
the one moment Convia holds somebody's password in the clear is when they sign
in successfully. A caller that sees this is true can re-hash and store the
result, which is the whole upgrade path.
*/
func Stale(stored Digest) bool {
	_, _, memory, iterations, parallelism, err := decode(stored)
	if err != nil {
		return true // Unreadable is as good a reason to replace it as weak.
	}

	return weaker(memory, iterations, parallelism)
}

// weaker reports whether derivation parameters fall short of the ones in force.
func weaker(memory uint32, iterations, parallelism uint8) bool {
	return memory < argonMemory || iterations < argonIterations || parallelism < argonParallelism
}

/*
NormalizePassword checks a password a person chose.

Length, and nothing else. Every composition rule ever written makes passwords
more predictable, because people satisfy them the same few ways — a capital at
the front and a digit at the end. What is refused instead is a control
character, which cannot have been typed deliberately and would be invisible in
every interface that later displays an error about it.
*/
func NormalizePassword(password Password) (Password, error) {
	length := utf8.RuneCountInString(string(password))

	switch {
	case length < MinimumPasswordLength:
		return "", ValidationError{
			Field:   "password",
			Message: fmt.Sprintf("A password must be at least %d characters.", MinimumPasswordLength),
		}
	case length > MaximumPasswordLength:
		return "", ValidationError{
			Field:   "password",
			Message: fmt.Sprintf("A password must not exceed %d characters.", MaximumPasswordLength),
		}
	case containsControl(string(password)):
		return "", ValidationError{
			Field:   "password",
			Message: "A password must not contain control characters.",
		}
	}
	return password, nil
}

// derive runs argon2id with the given parameters.
func derive(password Password, salt []byte, memory uint32, iterations, parallelism uint8) []byte {
	return argon2.IDKey([]byte(password), salt, uint32(iterations), memory, parallelism, argonKeyLength)
}

/*
encode renders a digest in the shape argon2 implementations agree on.

The parameters travel with the value rather than being assumed from this
package's constants, which is what makes raising the cost later a change that
affects new passwords without invalidating old ones.
*/
func encode(salt, key []byte) Digest {
	return Digest(fmt.Sprintf("$%s$v=%d$m=%d,t=%d,p=%d$%s$%s",
		digestVariant, argon2.Version, argonMemory, argonIterations, argonParallelism,
		base64.RawStdEncoding.EncodeToString(salt),
		base64.RawStdEncoding.EncodeToString(key)))
}

/*
decode reads a stored digest back into its parts.

Anything it cannot read is reported rather than guessed at. A digest from a
newer version of Convia, or a value somebody edited by hand, must not be
silently treated as a password that does not match — that would look like a
person mistyping and would send them to a reset they do not need.
*/
func decode(stored Digest) (salt, key []byte, memory uint32, iterations, parallelism uint8, err error) {
	return decodeAs(string(stored), digestVariant, ErrPasswordUnreadable)
}

/*
decodeAs reads any value in the encoded argon2 shape: a stored digest, or a
sealed key, which carries its derivation parameters the same way. What differs
is the variant expected and the error that says the value could not be read.
*/
func decodeAs(encoded, variant string, unreadable error) (salt, value []byte, memory uint32,
	iterations, parallelism uint8, err error) {
	fields := strings.Split(encoded, "$")
	if len(fields) != 6 || fields[0] != "" {
		return nil, nil, 0, 0, 0, unreadable
	}

	if fields[1] != variant {
		return nil, nil, 0, 0, 0, fmt.Errorf("%w: variant %q", unreadable, fields[1])
	}

	var version int
	if _, err := fmt.Sscanf(fields[2], "v=%d", &version); err != nil || version != argon2.Version {
		return nil, nil, 0, 0, 0, fmt.Errorf("%w: version %q", unreadable, fields[2])
	}

	memory, iterations, parallelism, err = parameters(fields[3], unreadable)
	if err != nil {
		return nil, nil, 0, 0, 0, err
	}

	if salt, err = base64.RawStdEncoding.DecodeString(fields[4]); err != nil {
		return nil, nil, 0, 0, 0, fmt.Errorf("%w: salt", unreadable)
	}

	if value, err = base64.RawStdEncoding.DecodeString(fields[5]); err != nil {
		return nil, nil, 0, 0, 0, fmt.Errorf("%w: value", unreadable)
	}

	return salt, value, memory, iterations, parallelism, nil
}

/*
parameters reads the cost field of an encoded digest.

Each of the three is parsed at the width argon2.IDKey accepts it in, so the
conversions at the end cannot truncate. Parsing them all as thirty-two bits and
checking afterwards states the same bound twice and leaves the conversion
itself unguarded, which is both harder to read and the shape a static analyser
is right to distrust.
*/
func parameters(field string, unreadable error) (memory uint32, iterations, parallelism uint8, err error) {
	/*
		The field is quoted back because an operator reading the log needs to
		see what was actually stored, and it carries no secret: the salt and the
		derived value are separate fields and neither reaches here.
	*/
	refuse := fmt.Errorf("%w: parameters %q", unreadable, field)

	pieces := strings.Split(field, ",")
	if len(pieces) != 3 {
		return 0, 0, 0, refuse
	}

	memoryDigits, memoryLabelled := strings.CutPrefix(pieces[0], "m=")
	iterationDigits, iterationsLabelled := strings.CutPrefix(pieces[1], "t=")
	parallelismDigits, parallelismLabelled := strings.CutPrefix(pieces[2], "p=")
	if !memoryLabelled || !iterationsLabelled || !parallelismLabelled {
		return 0, 0, 0, refuse
	}

	memoryValue, memoryErr := strconv.ParseUint(memoryDigits, 10, 32)
	iterationValue, iterationErr := strconv.ParseUint(iterationDigits, 10, 8)
	parallelismValue, parallelismErr := strconv.ParseUint(parallelismDigits, 10, 8)
	if memoryErr != nil || iterationErr != nil || parallelismErr != nil {
		return 0, 0, 0, refuse
	}

	/*
		Zero is refused for all three because argon2 has no meaning for it.
		A digest carrying one was not written by this package, and running it
		would derive a key no other implementation agrees with.
	*/
	if memoryValue == 0 || iterationValue == 0 || parallelismValue == 0 {
		return 0, 0, 0, refuse
	}

	return uint32(memoryValue), uint8(iterationValue), uint8(parallelismValue), nil
}
