package idempotency

import (
	"errors"
	"net/http"
	"strings"
	"testing"
)

func TestNormalizeKeyAcceptsAnOpaqueValue(t *testing.T) {
	/*
		A key is generated by the client and is meaningless to Convia.
		Constraining its shape would reject generators that are perfectly
		sound, so these are all accepted.
	*/
	cases := map[string]string{
		"a UUID":              "6f1a7b3e-2c4d-4e8a-9f01-2b3c4d5e6f70",
		"a random token":      "MXHJAY4MJNX2FO22XWJ3XNCKHT",
		"a namespaced key":    "orders/2026-09-08/create-room#1",
		"a single character":  "k",
		"the maximum length":  strings.Repeat("k", MaxKeyLength),
		"surrounded by space": "  spaced  ",
	}

	for name, value := range cases {
		t.Run(name, func(t *testing.T) {
			key, err := NormalizeKey(value)
			if err != nil {
				t.Fatalf("NormalizeKey(%q) error = %v", value, err)
			}
			if key != strings.TrimSpace(value) {
				t.Errorf("NormalizeKey(%q) = %q, want the value without surrounding space", value, key)
			}
		})
	}
}

/*
TestNormalizeKeyRefusesAKeyItCannotStore proves the bounds are enforced early.

Trimming to nothing is refused rather than treated as an absent header: a
client that sent whitespace asked for the guarantee, and serving the request
without it would be a false promise.
*/
func TestNormalizeKeyRefusesAKeyItCannotStore(t *testing.T) {
	cases := map[string]string{
		"empty":      "",
		"whitespace": "   \t ",
		"too long":   strings.Repeat("k", MaxKeyLength+1),
	}

	for name, value := range cases {
		t.Run(name, func(t *testing.T) {
			var validation ValidationError

			if _, err := NormalizeKey(value); !errors.As(err, &validation) {
				t.Fatalf("NormalizeKey(%q) error = %v, want a ValidationError", value, err)
			}
			if validation.Message == "" {
				t.Error("the refusal carried no message to report to the client")
			}
		})
	}
}

/*
TestTheDigestDistinguishesRequests is what makes a reused key detectable.

Two requests that differ anywhere a caller could have meant something different
must fingerprint differently, or a key would replay an answer to a question
that was never asked.
*/
func TestTheDigestDistinguishesRequests(t *testing.T) {
	base := Attempt{Method: http.MethodPost, Path: "/v1/rooms", Body: []byte(`{"name":"Standup"}`)}

	differing := map[string]Attempt{
		"a different body":   {Method: base.Method, Path: base.Path, Body: []byte(`{"name":"Retro"}`)},
		"a different path":   {Method: base.Method, Path: "/v1/calls", Body: base.Body},
		"a different method": {Method: http.MethodPut, Path: base.Path, Body: base.Body},
		"an empty body":      {Method: base.Method, Path: base.Path},
	}

	for name, other := range differing {
		t.Run(name, func(t *testing.T) {
			if other.digest() == base.digest() {
				t.Errorf("%s fingerprinted identically to the original request", name)
			}
		})
	}
}

/*
TestTheDigestIgnoresTheScopeAndKey keeps the fingerprint about the request.

The scope and key already address the record. Folding them into the digest
would make a request appear to differ from itself.
*/
func TestTheDigestIgnoresTheScopeAndKey(t *testing.T) {
	first := Attempt{Scope: "app_A", Key: "one", Method: http.MethodPost, Path: "/v1/rooms", Body: []byte(`{}`)}
	second := Attempt{Scope: "app_B", Key: "two", Method: http.MethodPost, Path: "/v1/rooms", Body: []byte(`{}`)}

	if first.digest() != second.digest() {
		t.Error("the same request fingerprinted differently for two callers")
	}
}

/*
TestTheDigestCannotBeConfusedByFieldBoundaries proves the parts stay separate.

Concatenating without a separator would let one request's method and path run
into another's and produce the same input, which would make two different
requests indistinguishable to a key.
*/
func TestTheDigestCannotBeConfusedByFieldBoundaries(t *testing.T) {
	first := Attempt{Method: "POST", Path: "/v1/rooms"}
	second := Attempt{Method: "POST/v1", Path: "/rooms"}

	if first.digest() == second.digest() {
		t.Error("two requests differing only in where the method ends fingerprinted identically")
	}
}

/*
TestOnlyAnAnswerTheServerStandsBehindIsReplayed is the retention policy.

A refusal is kept because repeating the request unchanged would be refused
again. A server error or a rate-limited refusal is not, because storing one
would turn a transient failure into a permanent one: every retry inside the
retention window would be answered with the failure rather than allowed to
succeed.
*/
func TestOnlyAnAnswerTheServerStandsBehindIsReplayed(t *testing.T) {
	replayed := []int{
		http.StatusOK,
		http.StatusCreated,
		http.StatusNoContent,
		http.StatusBadRequest,
		http.StatusForbidden,
		http.StatusNotFound,
		http.StatusConflict,
		http.StatusPreconditionFailed,
	}
	for _, status := range replayed {
		if !worthReplaying(status) {
			t.Errorf("worthReplaying(%d) = false, want a settled answer to be replayed", status)
		}
	}

	retried := []int{
		http.StatusTooManyRequests,
		http.StatusInternalServerError,
		http.StatusBadGateway,
		http.StatusServiceUnavailable,
	}
	for _, status := range retried {
		if worthReplaying(status) {
			t.Errorf("worthReplaying(%d) = true, want a retry to be a real attempt", status)
		}
	}
}
